### ISSUE TITLE
io.js support

### ISSUE THREAD

**Issue by callumacrae** [gulpjs/gulp-cli#10]
As far as I can see, getting Node to use io.js would just just be a case of [changing the hashbang](https://github.com/gulpjs/gulp-cli/blob/master/bin/gulp.js#L1) (and the one in gulp). Liftoff has no problems with io.js: tkellen/node-liftoff#30

Is there a way to support io.js which doesn't involve switching the entire project to use it? Say, if I want to use io.js in my gulpfile.js.

**Comment by tkellen** [comment]
io.js aliases node, it should work out of the box.  have you tried this?

**Comment by callumacrae** [comment]
d'oh. No, I haven't: I didn't want to try io.js until I knew that it wouldn't break anything.

**Comment by julien** [comment]
Hi, any update on this?

**Comment by callumacrae** [comment]
@julien Check out gulpjs/gulp#873
