### ISSUE TITLE
Cant use gulp with free arguments

### ISSUE THREAD

**Issue by zxqfox** [gulpjs/gulp-cli#104]
Trying to run `gulp task -- param`.

Parsing `param` with `minimist` in `gulpfile.js`, but `gulp-cli` still handles this as a task.
What I should do?

**Comment by contra** [comment]
@phated We should ignore anything after `--` to confirm to unix standards right? I'm surprised our parser doesn't already pick up on that, and instead puts them in `_`

**Comment by zxqfox** [comment]
@contra It's not unix, it's bash only. I've provided links about that in #103.

I'd like to have behaviour as close to `npm` as possible but I was surprised you close an issue so fast ;-D

**Comment by phated** [comment]
If yargs doesn't handle the `--` correctly, that's an issue for them.  I'm pretty sure it does (tested it over a year ago so I don't remember specifics).

**Comment by zxqfox** [comment]
@phated What means correctly? It does it like `bash`, but not like `npm`. Is this correctly for `gulp`? And why?

**Comment by phated** [comment]
`npm` is a custom implementation that was introduce in npm@3, we aren't going to implement that because we follow bash whenever possible.

**Comment by zxqfox** [comment]
Why?
