### ISSUE TITLE
Allow usage from JS or extract data retrieval to another package

### ISSUE THREAD

**Issue by flying-sheep** [gulpjs/gulp-cli#112]
I’d like to do

```js
import { tasks } from 'gulp-cli'

const taskTree = tasks('some/dir')
const taskList = tasks('path/to/gulpfile.js', /*depth =*/ 1)
```

**Comment by phated** [comment]
Gulp exposes the methods you want. Just use it programmatically.

**Comment by flying-sheep** [comment]
Oh sorry. I thought because of the version stub that broad compatibility is something limited to gulp-cli.

Will gulp 4 be able to load and spit out a task list for old gulpfiles?
