### ISSUE TITLE
[Question] Get custom flag value inside task

### ISSUE THREAD

**Issue by jaroslw** [gulpjs/gulp-cli#116]
What is a recommended way to grab custom flag value passed in CLI? In documentation there is only mentioned how to define custom flags. 

For example: I would like to pass port and livereload toggle value to the `serve` task. Any help much appreciated :)
```js
function serve() {
  plugins.connect.server({
    root: 'build',
    livereload: true
  });
}
serve.description = 'Desc';
serve.flags = {
  '--port': 'Port used to run the application server (overrides config.js value).',
  '--livereload': 'Enable/disable live reload on file changes (overrides config.js value).',
};

gulp.task('serve', ['watch'], serve);
```

**Comment by phated** [comment]
Support questions should be directed to StackOverflow. There's a recipe for this too.
