### ISSUE TITLE
The file .gulp.json is not working.

### ISSUE THREAD

**Issue by NextSeason** [gulpjs/gulp-cli#117]
I added a `.gulp.json` file under the root dir of the project, but it's not working.

```json
$cat .gulp.json
{
    "flags" : {
        "gulpfile" : "build/gulpfile.js"
    }
}
$gulp
[20:28:02] No gulpfile found
```

**Comment by sttk** [comment]
@NextSeason What version of gulp and gulp-cli do you use?

The feature you want is available from the version 1.3.0 of gulp-cli.

**Comment by NextSeason** [comment]
@sttk thanks for your reply. 

```
gulp -v
[21:00:40] CLI version 3.9.1
[21:00:40] Local version 3.9.1
``

**Comment by sttk** [comment]
@NextSeason Maybe you didn't install gulp-cli. Please try to install the latest gulp-cli apart from gulp.

**Comment by NextSeason** [comment]
@sttk thanks a lot, but it still not working as same as running it with command `gulp --gulpfile build/gulpfile.js --cwd .`. 

Everything is going well when I running `gulp` with the command line,  but if I just running `gulp` with the `.gulp.json`, it would ask me to install a local `gulp` in the dir.

```
$gulp
[22:07:16] Local gulp not found in /Users/L/workspace/project
[22:07:16] Try running: npm install gulp

$gulp --gulpfile build/gulpfile.js --cwd .
No Additional Settings File

[22:07:51] Using gulpfile /Users/L/workspace/project/build/gulpfile.js
[22:07:51] Starting 'all'...
✔ Initialized package pages/topic/create
✔ Initialized package pages/topic/topic
✔ Initialized package pages/tag/create
✔ Initialized package pages/tag/tag
```

Thank you for your patience.

**Comment by sttk** [comment]
@NextSeason Did you install gulp-cli globally? 

The recommended install method is 

```
$ npm install --global gulp-cli
$ npm install --save-dev gulp
```

See [getting-started.md](https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md).

**Comment by phated** [comment]
@NextSeason can you confirm @sttk's last comment solves the issue.  Otherwise I'm going to close this as inactive.

**Comment by NextSeason** [comment]
@sttk I am sorry, I didn't reply him and you can close it now.
thank you very much.

**Comment by sttk** [comment]
@NextSeason OK. I'll close this.
