### ISSUE TITLE
copy-props

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#123]
@sttk I noticed that `copy-props` was major-bumped to 2.x awhile back for an API change.  Can you update it here and address the usage changes?

**Comment by sttk** [comment]
Sorry, I forgot to update about this.
I'm working on it.

**Comment by phated** [comment]
Thanks!

**Comment by erikkemperman** [comment]
@phated @sttk I already did some of the things you are requesting in recent issues -- so if you want to you could just cherry-pick from that PR. In this case, for copy-props, https://github.com/gulpjs/gulp-cli/pull/119/commits/295eaa763370b7dc210fbdaf76ffad7e5e690b9b
