### ISSUE TITLE
Replace tildify

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#124]
Not sure if there's a good replacement module.  Might need to create one.

**Comment by VuongN** [comment]
I'll take this one. Could you give me a bit more thoughts on:
1. Was there an issue with current tildify package or is it just a matter of tightening of the code for v4? I see that there is another package dependency (os-home) package.
2. Does this need to be in a separate package or can it go straight into gulp itself? It's pretty small util function.

There are two references to this tildify utility function, (this package and https://github.com/atom/fs-plus/blob/master/src/fs-plus.coffee#L71-L81).  Both are extremely small.  At the risk of creating yet another package that handles such a tiny thing, I figured I ask.

Best,

-V.

**Comment by phated** [comment]
I'm actually wrapping this up shortly.  A new module needed to be created that I'm finishing.
