### ISSUE TITLE
Replace chalk

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#125]
I'm thinking we should replace chalk with individual `ansi-*` modules from @jonschlinkert: https://github.com/jonschlinkert?utf8=%E2%9C%93&tab=repositories&q=ansi&type=&language=

**Comment by contra** [comment]
Why? Sounds like a ton of overhead in deps and increased code complexity.

**Comment by phated** [comment]
Because chalk is overkill and we are removing sindre deps due to desupporting node 0.10
