### ISSUE TITLE
Replace wreck

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#126]
There's probably a smaller and es5-friendly request library.

**Comment by tdeschryver** [comment]
Did you had something in mind?
Because I couldn't find one at first sight, or they dropped node 0.10.

Would it be an option to write one ourselves?

**Comment by phated** [comment]
@tdeschryver I don't really have any recommendations.  Maybe https://www.npmjs.com/package/http-basic?  Not sure if @ForbesLindesay wants to support node 0.10

**Comment by phated** [comment]
Maybe https://github.com/brycebaril/client-request

**Comment by phated** [comment]
Or maybe something as simple as https://github.com/fent/node-miniget

**Comment by ForbesLindesay** [comment]
I don't support any un-maintained node.js versions. I'd encourage as many module authors as possible to follow suit.

**Comment by terinjokes** [comment]
We only use it for fetching the blacklist, afaict. Why not just use the built-in HTTP client?

**Comment by phated** [comment]
@terinjokes can you review my implementation at https://github.com/gulpjs/gulp-cli/commit/ea747211b3357f923afa19bc1f11fa8982783f59?

**Comment by terinjokes** [comment]
@phated It looks reasonable to me.
