### ISSUE TITLE
When will 4.0 be released

### ISSUE THREAD

**Issue by ibc** [gulpjs/gulp-cli#13]
Sorry for opening an issue for such a question. Which is the ETA for `gulp-cli` 4.0 (the version that is supposed to run any local `gulp` version)?

**Comment by phated** [comment]
There is no ETA because we are blocked by #7 - We are considering publishing an alpha sooner though.

**Comment by geirsagberg** [comment]
Any updates on this in light of #7 closed and NPM 4 released?

**Comment by phated** [comment]
We are very close to the 1.0 release of the CLI.

__Reminder:__ Gulp is built by volunteers. If you want to speed up the release, see if you can help with any of these issues: https://github.com/gulpjs/gulp/issues?q=is%3Aopen+is%3Aissue+label%3Agulp4

Check out a few of the previous issues opened for more info:

https://github.com/gulpjs/gulp/issues/1068
https://github.com/gulpjs/gulp/issues/968
https://github.com/gulpjs/gulp/issues/865
