### ISSUE TITLE
Question: How can I use Custom Metadata?

### ISSUE THREAD

**Issue by yuheiy** [gulpjs/gulp-cli#136]
In README:

```javascript
function build() { ... }
build.description = 'Build entire project.';
build.flags = {
  '--prod': 'Builds in production mode (minification, etc).'
};
// gulp 3.x
gulp.task('build', build);
// gulp 4.x
gulp.task(build);
```

## How can I execute command?

> \> gulp [flags] \<task\> \<task\>...

When I executed `gulp --prod build`, it says `Task never defined: default`.

## How can I read values for flags in `gulpfile.js`

> All other flags are for tasks to use if needed.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.  The feature you are asking about is just used for documentation purposes; you have to use node paradigms to read your flags.
