### ISSUE TITLE
Documentation for per-task flags could be improved

### ISSUE THREAD

**Issue by AlecBenzer** [gulpjs/gulp-cli#140]
#39 discusses per-task flags a bit. The [documentation for it](https://github.com/gulpjs/gulp-cli#custom-metadata) gives the following example usage:

```js
function build() { ... }
build.description = 'Build entire project.';
build.flags = {
  '--prod': 'Builds in production mode (minification, etc).'
};
// gulp 3.x
gulp.task('build', build);
// gulp 4.x
gulp.task(build);
```

But... this doesn't seem to show how you're actually supposed to *use* the flags? I imagine it's something like:

```js
function build() {
  if (build.flags['--prod']) {
    doMinifiedBuild();
  } else {
    doRegularBuild();
  }
}
build.description = 'Build entire project.';
build.flags = {
  '--prod': 'Builds in production mode (minification, etc).'
};
// gulp 3.x
gulp.task('build', build);
// gulp 4.x
gulp.task(build);
```

on the CLI:

```bash
gulp build --prod
```

Is that right? Can this be documented?

**Comment by phated** [comment]
@AlecBenzer That's not correct at all.  The feature you are looking at is just for documenting your gulpfiles for other people's usage.  It doesn't expose any sort of usage and you need to use node's `process.argv` directly or a module like minimist or yargs, etc.

**Comment by AlecBenzer** [comment]
Ok; I'm confused then, what is:

```js
build.flags = {
  '--prod': 'Builds in production mode (minification, etc).'
};
```

mean to communicate then? That a flag named `--prod` exists and is implemented via some other mechanism (yargs, etc.)?
