### ISSUE TITLE
upgrading from gulp to gulp-cli causes autocompletion error (4.0 branch)

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp-cli#15]
`gulp autocompletion rules for 'bash' not found` with `eval "$(gulp --completion=bash)"` in the bashrc which is what we used to recommend. no docs available for how to use autocompletion on any repos now afaik

**Comment by heikki** [comment]
I'll take this one if you haven't started already.

**Comment by contra** [comment]
Yep haven't looked into it yet - feel free!

**Comment by contra** [comment]
@heikki Nicely done :+1:
