### ISSUE TITLE
Failed to load external module @babel/register

### ISSUE THREAD

**Issue by lipis** [gulpjs/gulp-cli#150]
```
$ gulp -v
[14:50:32] Failed to load external module @babel/register
[14:50:32] Requiring external module babel-register
[14:50:32] CLI version 2.0.1
[14:50:32] Local version 4.0.0
```

Because the first line is an error I cannot use gulp with husky/lint-staged precommit hooks.. this have been around for couple of years now. Can we do something about it? Or at least not throwing an error? (some say it's a warning and everything is fine.. but warnings are not red)

**Comment by phated** [comment]
@lipis nothing about the color red should fail a precommit hook - hopefully your tooling only looks for exit code 1.  We log on stderr so poor tooling might fail if there is output on stderr.

Ref https://github.com/gulpjs/gulp-cli/issues/142
