### ISSUE TITLE
[enhancement] more flags to be configurable via a .gulp file

### ISSUE THREAD

**Issue by marcelh-gh** [gulpjs/gulp-cli#167]
for example the `require `flag

**Comment by sttk** [comment]
@marcelh-gh We are planning to support `require` flag via `.gulp.js` (#108), but to do this, it is needed to modify `js-liftoff` ([js-liftoff#93](https://github.com/js-cli/js-liftoff/pull/93/files), etc.)

About `cwd` flag, we have some issues (#109, #146, etc.)  

About some of other flags, we will address to support. Do you request any other flags? We'll try it or welcome your PR.

**Comment by marcelh-gh** [comment]
@sttk great to hear that you are already on it! :-)
I was looking for this to have `--require tsconfig-paths/register ` everytime I run gulp.
Maybe it would be a good idea to do that always, just like you already register ts-node when the gulpfile is written in TypeScript.

**Comment by phated** [comment]
The `flags.require` property is now supported in v2.1.0!
