### ISSUE TITLE
Gulp fails to load '@babel/register'

### ISSUE THREAD

**Issue by sgen** [gulpjs/gulp-cli#171]
I'm attempting to use `@babel/register` instead of `babel-register`. However, Gulp fails to load it.

Replication instructions: 

Initialize `npm`, `npm install gulp@next @babel/register @babel/preset-es2015`, setup `.babelrc` and `gulpfile.babel.js` and run `gulp`.

`ls` clearly shows `node_modules/@babel/register` is installed.

```bash
npm init

npm install --save-dev gulp@next @babel/register @babel/preset-es2015

cat << EOF >> .babelrc
{
  "presets": [ "es2015" ]
}
EOF

cat << EOF >> gulpfile.babel.js
export default function build() {
  return Promise.resolve();
}
EOF

gulp
# Outputs:
# [xx:xx:xx] Failed to load external module @babel/register
# [xx:xx:xx] Failed to load external module babel-register
# [xx:xx:xx] Failed to load external module babel-core/register
# [xx:xx:xx] Failed to load external module babel/register
# /home/sgen/Projects/.srcs/github.com/sgen/gulp-babel-register-namespace-issue/gulpfile.babel.js:1
# (function (exports, require, module, __filename, __dirname) { export default function build() {
#                                                               ^^^^^^

# SyntaxError: Unexpected token export
#     at createScript (vm.js:80:10)
#     at Object.runInThisContext (vm.js:139:10)
#     at Module._compile (module.js:616:28)
#     at Object.Module._extensions..js (module.js:663:10)
#     at Module.load (module.js:565:32)
#     at tryModuleLoad (module.js:505:12)
#     at Function.Module._load (module.js:497:3)
#     at Module.require (module.js:596:17)
#     at require (internal/module.js:11:18)
#     at execute (/home/user/.npm/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)

ls node_modules/@babel/register/lib/index.js
# outputs
# node_modules/@babel/register/lib/index.js
```

[Reproduction example](https://github.com/sgen/gulp-babel-register-namespace-issue) (Clone, `npm install` and run `gulp`)

**Comment by sttk** [comment]
According to the pages of [@babel/register](https://babeljs.io/docs/en/next/babel-register.html) and [@babel/preset-es2015](https://babeljs.io/docs/en/babel-preset-es2015) in babel's site, you need to install @babel/core, and should install @babel/preset-env instead of @babel/preset-es2015.

For more information, please direct questions to StackOverflow or babel's support. It seems that this is not gulp's issue.

**Comment by sgen** [comment]
@babel/core @babel/register and @babel/preset-env does it.

**Comment by mylastore** [comment]
if you @babel/core @babel/register and @babel/preset-env then you get this 
``
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/storage/projects/client/node_modules/gulp-babel/index.js:7:15)

``

**Comment by phated** [comment]
@mylastore please inspect your stack trace. It explicitly states your problem was thrown inside `gulp-babel` which isn't part of gulp.
