### ISSUE TITLE
Issue updating with NVM

### ISSUE THREAD

**Issue by ericwbailey** [gulpjs/gulp-cli#175]
Hi there,

I was following the instructions outlined in [this post](https://medium.com/gulpjs/gulp-sips-command-line-interface-e53411d4467) and ran into a problem:

Removing global gulp by running `npm rm --global gulp` works, but attempting to install `gulp-cli` via `npm install --global gulp-cli` generates the following error message:

``` 
/Users/usr/.nvm/versions/node/v10.2.1/bin/gulp -> /Users/usr/.nvm/versions/node/v10.2.1/lib/node_modules/gulp-cli/bin/gulp.js
npm ERR! path /Users/usr/.nvm/versions/node/v10.2.1/share/man/man1/gulp.1
npm ERR! code EEXIST
npm ERR! Refusing to delete /Users/usr/.nvm/versions/node/v10.2.1/share/man/man1/gulp.1: ../../../lib/node_modules/gulp/gulp.1 symlink target is not controlled by npm /Users/usr/.nvm/versions/node/v10.2.1/share/man/man1
npm ERR! File exists: /Users/usr/.nvm/versions/node/v10.2.1/share/man/man1/gulp.1
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/usr/.npm/_logs/2018-11-30T21_00_08_775Z-debug.log
```

Have you encountered something like this before?

**Comment by phated** [comment]
The error above happens when you have messed up permissions.  You likely originally installed gulp with sudo, then removed it without sudo which left the manpage dangling and now it can't be replaced by the new install.

**Comment by ericwbailey** [comment]
I'll give that a shot, thanks.

**Comment by phated** [comment]
@ericwbailey you should be able to check permissions on the file that it says it can't remove and then use proper permissions to remove it.

**Comment by ericwbailey** [comment]
That seemed to do the trick, thanks again!
