### ISSUE TITLE
Log only the "Finished" messages and not the "Starting" ones

### ISSUE THREAD

**Issue by marcofugaro** [gulpjs/gulp-cli#177]
Hey, it would be really useful if I could tell Gulp to log only when a task is done, not when it starts. 
I don't actually care when the task starts during development. I only care about how much time it took and if it ran successfully.

I've tried the `log-level` option and it just turns the starting/finished logs on or off.

What do you think?

**Comment by sttk** [comment]
@marcofugaro Now we consider that gulp-cli enable to customize colors and messages of logs. If it is achieved, gulp-cli will be able to output an empty line too instead of starting log.

**Comment by phated** [comment]
@sttk I think we should avoid logging any line that is "falsey" so they can set the theming to `false` to disable.

**Comment by sttk** [comment]
@phated To do that, we should modify `lib/shared/log/log-levels.js` in PR #161 as follows:

* L33: `log.on(level, console.error);` → `log.on(function(s) { if (s) console.error(s): });`
* L35: `log.on(level, console.log);` → `log.on(function(s) { if (s) console.log(s): });`
