### ISSUE TITLE
Question: does gulp-cli avoid having glulp and gulp-modules linked?

### ISSUE THREAD

**Issue by BananaAcid** [gulpjs/gulp-cli#179]
Does gulp-cli avoid having glulp and gulp-modules linked into the gulp file folder (works with a globally installed gulp and globally installed gulp-modules)?

this should be added to the Readme (or clarified if I missed it).

**Comment by phated** [comment]
No.  gulp-cli exposes the `gulp` command to the command line.  Due to Node's module resolution system, you need to have gulp installed locally into your project to use any of the methods that gulp provides (like `src`, `dest`, etc).
