### ISSUE TITLE
cannot install with npm

### ISSUE THREAD

**Issue by ray007** [gulpjs/gulp-cli#180]
I tried to install new gulp with instructions from [gulp-quickstart](https://gulpjs.com/docs/en/getting-started/quick-start), but it does not work:
`npm install --global gulp-cli` results in
```
npm ERR! Unexpected end of JSON input while parsing near '...mckVt2DO5KIEuctTGJAyd'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2019-02-18T09_20_54_979Z-debug.log
```
Since installing modules other than gulp/gulp-cli works, there seems to be a problem with the gulp published to npmjs.
All this on Win10 x64.

**Comment by ray007** [comment]
Update: I did verify the problem exists only in Windows `cmd`, doing the install in the linux subsystem works.
Which doesn't help me, since the target build system needs to run in Windows `cmd`.

**Comment by ray007** [comment]
I was asked for versions in the gitter chatroom, so also more info here:
```
$ node --version
v10.15.1

$ npm --version
6.8.0
```
Looking for the JSON end in the logfile, I find the following line:
```
154 silly fetchPackageMetaData error for rechoir@^0.6.2 Unexpected end of JSON input while parsing near '...mckVt2DO5KIEuctTGJAyd'
```

**Comment by ray007** [comment]
Something very strange just happened: to get more information, I added `--verbose` to the install command, and suddenly it worked.
Any explanation for this?

**Comment by phated** [comment]
Sounds like your npm was in a weird state.  Glad you got it solved.

**Comment by parduman** [comment]
> Something very strange just happened: to get more information, I added `--verbose` to the install command, and suddenly it worked.
> Any explanation for this?

i got into same problem i  got it worked by adding sudo in front and --verbose in end
