### ISSUE TITLE
Support a `description` property on task functions

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#19]
If we see a property named `description` on a task function, we should print it when using the `--tasks` flag.

ref gulpjs/gulp#591

**Comment by louisremi** [comment]
I have implemented support for the `.description` property both in master (see #20 )  and 4.0 (see #21 ).
To make it simpler to use this feature, I propose adding a `.describe()` method to gulp-util, see [gulp/gulp-util/issues/90](https://github.com/gulpjs/gulp-util/issues/90).

Waiting for your feedback : )
