### ISSUE TITLE
Need more tests

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#2]
We need more exec tests.

**Comment by phated** [comment]
Anyone willing to write some tests for the CLI?  I'd like to have some more before 1.0 (which is coming very soon)

**Comment by erikkemperman** [comment]
Noticed that currently the tests for `gulp-cli#4.0` use a dev dependency on `gulp>=3.8.10`
Looks like an artifact from 0.3.0? Shouldn't that be `gulpjs/gulp#4.0` or something?

**Comment by phated** [comment]
@erikkemperman I think that the gulp dep should actually just be installed through a travis matrix instead of having it as a devDep (this is in response to an error someone got with npm 3 about installing gulp as a dependency of gulp).  Thoughts?

**Comment by erikkemperman** [comment]
Not on Travis matrices, unfamiliar.

I have this working
https://github.com/erikkemperman/gulp-cli/commit/ccad33282ac28028786af1b55024b401255f61db

But I might have been cheating with symlinks.

**Comment by erikkemperman** [comment]
@phated Your remark about NPM3, was that basically as reported in [#7](https://github.com/gulpjs/gulp-cli/issues/7)? If I read that correctly, it has been fixed upstream?

Above patch works for me, using stock NPM (2.14.4, from `make install` against latest node sources). But I have cross-linked my local `gulp#4.0` and `gulp-cli#4.0` before doing `npm install` and `npm test` on those.

Anyway, whatever resolution is found eventually on inter-dependencies between gulp and gulp-cli, I can't imagine the current state of affairs (gulp-cli#4.0 depending on gulp3 for its testst) to be right...

**Comment by Romanx** [comment]
I'd be willing to contribute some tests but I'm not sure what functionality you'd want testing specifically. If you'd like to give me a hit-list I'm happy to tackle it.

**Comment by phated** [comment]
@Romanx we need unit tests on all of the functions in the `lib/` directory and we can use integration tests on all the CLI options (listed in the readme of 4.0 branch).

**Comment by Romanx** [comment]
@phated we consider this done or should we work on running 3.8+ and 4.0+ side by side in this ticket?

**Comment by phated** [comment]
@Romanx going to leave this open as something that any one can jump into and create some tests for.  I think we are in a good place to release the 1.0 of gulp-cli with your tests added.

**Comment by sttk** [comment]
@phated I wrote some unit test codes for `logTasks`, for PR #50. They are placed in [my repository](https://github.com/sttk/gulp-cli/tree/test_for_gulp_tasks/test/logTasks).

However, they are written in my own way. Are there an unified way and a location rule for unit test codes?

**Comment by phated** [comment]
We have proper code coverage now (thanks to @sttk in #99!) so needed tests should be easier to identify. 😃

**Comment by phated** [comment]
We have something like 95% code coverage now.  I don't think this broad "make more tests" issue is needed anymore.  We can identify missing tests and create individual issues for them.
