### ISSUE TITLE
Remove leading ellipsis in .flags string when running --tasks

### ISSUE THREAD

**Issue by yoanmalie** [gulpjs/gulp-cli#206]
Hello,
Not a bug but a question and suggestion here. I hope i'm in the right repository.

Why there is leading ellipsis added on the `task.flags` description when running `gulp --tasks`? Can we just remove it? So we can add whatever if we want or keep it simply clean.

![image](https://user-images.githubusercontent.com/3357171/80597893-ca904980-8a28-11ea-85f7-e00c527ae63d.png)

Thanks!

**Comment by phated** [comment]
This design was contributed by a designer that volunteered time for us. We implemented based on their recommendation.

We'll consider adding the ability for you to configure this as part of our theming and translation work.

**Comment by rootwork** [comment]
Personally I'd like to see this be something minimal, like two spaces, as the default. And the ellipsis could be the optional theming setting.
