### ISSUE TITLE
Dependency Update.

### ISSUE THREAD

**Issue by assunluis80** [gulpjs/gulp-cli#208]
On installing gulp, NPM shows the follwing mesage:

![Low_Severity](https://user-images.githubusercontent.com/8853276/81522942-3ab1a000-9344-11ea-871b-2ab514b0387f.png)

After installation running the following command: `npm run`, outputs:

![NPM_Audit](https://user-images.githubusercontent.com/8853276/81522765-96c7f480-9343-11ea-8b9c-33b31ee9ebe6.png)

**Comment by phated** [comment]
We are no longer accepting issues like this and I must issue you a 1 day ban. Sorry.
