### ISSUE TITLE
upgrade package.json

### ISSUE THREAD

**Issue by zhangchenglin** [gulpjs/gulp-cli#221]
D:\PhpstormProjects\GitHub\gulp-cli>ncu
Checking D:\PhpstormProjects\GitHub\gulp-cli\package.json
[====================] 31/31 100%

 ansi-colors          ^1.0.1  →   ^4.1.1
 concat-stream        ^1.6.0  →   ^2.0.0
 copy-props           ^2.0.1  →   ^2.0.4
 fancy-log            ^1.3.2  →   ^1.3.3
 interpret            ^1.4.0  →   ^2.2.0
 isobject             ^3.0.1  →   ^4.0.0
 mute-stdout          ^1.0.0  →   ^1.0.1
 pretty-hrtime        ^1.0.0  →   ^1.0.3
 yargs                ^7.1.0  →  ^16.0.3
 babel-register       ^6.5.1  →  ^6.26.0
 coveralls            ^3.0.3  →   ^3.1.0
 eslint              ^2.13.1  →  ^7.10.0
 eslint-config-gulp   ^3.0.1  →   ^5.0.0
 expect              ^1.20.2  →  ^26.4.2
 gulp                 ^4.0.0  →   ^4.0.2
 gulp-test-tools      ^0.6.1  →   ^0.6.2
 marked-man           ^0.2.1  →   ^0.7.0
 mocha                ^3.2.0  →   ^8.1.3
 nyc                 ^13.3.0  →  ^15.1.0
 rimraf               ^2.6.1  →   ^3.0.2
 semver               ^5.7.1  →   ^7.3.2

Run ncu -u to upgrade package.json

---

Upgrade the package version number to the version you think is appropriate. There are so many old versions here, but errors will be reported, such as
https://github.com/advisories/GHSA-p9pc-299p-vxgp

This has been a report for several months. I don't know when the so-called gulp5 will be released, but I think the package name should be updated as follows. The specific version number is uncertain, and at least keep it healthy.

 gulp                 ^4.0.0  →   ^4.0.2

 yargs                ^7.1.0  →  ^16.0.3
 semver               ^5.7.1  →   ^7.3.2

**Comment by phated** [comment]
Read the issue template.
