### ISSUE TITLE
Gulp-cli 2.2.0 fails with `Task never defined: default`

### ISSUE THREAD

**Issue by mrleblanc101** [gulpjs/gulp-cli#223]
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [ ] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [ ] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?
The default task should be loaded from the `module.exports` and be ran normally.
This is working when I'm using `gulp-cli@2.1.0` but not `gulp-cli@2.2.0` or above

### What actually happened?
The default task is not found and not ran

### Please give us a sample of your gulpfile

```js
import gulp from 'gulp'

import utils from './utils'
import scripts from './scripts'
import styles from './styles'
import images from './images'
import svgs from './svgs'
import fonts from './fonts'
import assets from './assets'
import templates from './templates'
import server from './server'

import config from '../config/config.js'

let build = gulp.series( utils.clean, gulp.parallel( gulp.series( styles.check, styles.build ), (config.legacyBuild ? gulp.series( scripts.check, scripts.legacy.build ) : gulp.series( scripts.check, scripts.build )),  gulp.series( images.check, images.copy), gulp.series( svgs.copy, svgs.sprite), gulp.series(templates.json,templates.build), fonts.copy, assets.copy ) )
build.displayName = 'Building assets'

let watch = gulp.parallel( templates.watch , styles.watch, ( config.legacyBuild ? scripts.legacy.watch : scripts.watch ), images.watch, svgs.watch, fonts.watch, assets.watch)
watch.displayName = 'Watching assets'

let dev = gulp.series( build, gulp.parallel(server.start, watch) )
dev.displayName = 'Starting local webserver'

let start = gulp.series( build, server.start )
start.displayName = 'Starting local webserver'

let optimize = gulp.parallel( images.optimize, svgs.optimize )
optimize.displayName = 'Optimizing assets'

module.exports = {
    'default': dev,
    dev,
    start,
    build,
    optimize,
}

```

### Terminal output / screenshots

<img width="644" alt="Capture d’écran, le 2020-10-08 à 19 35 51" src="https://user-images.githubusercontent.com/17392251/95524234-d0f2fc00-099e-11eb-84d7-6e0a0dedc302.png">

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: MacOS Catalina 10.15.7
* node version (run `node -v`): v12.18.4
* npm version (run `npm -v`): v12.18.4
* gulp version (run `gulp -v`): v4.0.2

**Comment by mrleblanc101** [comment]
Some aditionnal informaiton: 
```js
module.default = dev; // doesn't work
module.default = gulp.series( build, gulp.parallel(server.start, watch) ); // doesn't work
module.exports.default = dev; // doesn't work
module.exports.default = gulp.series( build, gulp.parallel(server.start, watch) ); // this works for some reason
```

**Comment by sttk** [comment]
@mrleblanc101  I tried, and this is my result.

```
% node -v                                                                       
v12.18.4
% npm init
% npm i -D gulp @babel/core @babel/preset-env @babel/register
% npx gulp -v
CLI version: 2.3.0
Local version: 4.0.2
% cat .babelrc
{
  "presets": [
    "@babel/preset-env"
  ]
}
% cat gulpfile.babel.js
import gulp from 'gulp'

let build = cb => { console.log('build'); cb(); }
let watch = cb => { console.log('watch'); cb(); }
let dev = cb => { console.log('dev'); cb(); }
let start = cb => { console.log('start'); cb(); }
let optimize = cb => { console.log('optimize'); cb(); }

module.exports = {
  'default': dev,
  dev,
  start,
  build,
  optimize,
}
% npx gulp
[13:19:59] Requiring external module @babel/register
[13:19:59] Using gulpfile ~/gulp-cli#223/gulpfile.babel.js
[13:19:59] Starting 'default'...
dev
[13:19:59] Finished 'default' after 1.31 ms
%
```

**Comment by sttk** [comment]
Sorry. This issue's title says "Gulp-cli 2.2.0", but I retried on 2.2.0 and got same result.

```
% npx gulp -v
CLI version: 2.2.0
Local version: 4.0.2
ryusi:~/home/oss/github/gulpjs/gulp-support/gulp-cli#223
% npx gulp
[13:47:05] Requiring external module @babel/register
[13:47:05] Using gulpfile ~/gulp-cli#223/gulpfile.babel.js                                          
[13:47:05] Starting 'default'...
dev
[13:47:05] Finished 'default' after 1.25 ms
```

**Comment by mrleblanc101** [comment]
2.2.0 or anything higher fails. 2.1.0 works fine.
Maybe it has something to do with how we split the task in seperate files.
We use `index.js` instead of `gulpfile.babel.js`, but since we have `--require @babel/register` in the command I don't think it's needed in the name.
```
  "scripts": {
    "start": "NODE_ENV=development gulp --require @babel/register --gulpfile tasks",
  },
```
<img width="300" alt="Capture d’écran, le 2020-10-10 à 16 27 31" src="https://user-images.githubusercontent.com/17392251/95664423-b8592200-0b15-11eb-9eae-bf70c581cf60.png">

**Comment by mrleblanc101** [comment]
I've narrowed it down and the issue seems to come from #189 
If I remove all `displayName`, everything works fine.
```
import gulp from 'gulp'

import utils from './utils'
import scripts from './scripts'
import styles from './styles'
import images from './images'
import svgs from './svgs'
import fonts from './fonts'
import assets from './assets'
import templates from './templates'
import server from './server'

import config from '../config/config.js'

let build = gulp.series( utils.clean, gulp.parallel( gulp.series( styles.check, styles.build ), (config.legacyBuild ? gulp.series( scripts.check, scripts.legacy.build ) : gulp.series( scripts.check, scripts.build )),  gulp.series( images.check, images.copy), gulp.series( svgs.copy, svgs.sprite), gulp.series(templates.json,templates.build), fonts.copy, assets.copy ) )
// build.displayName = 'Building assets'

let watch = gulp.parallel( templates.watch , styles.watch, ( config.legacyBuild ? scripts.legacy.watch : scripts.watch ), images.watch, svgs.watch, fonts.watch, assets.watch)
// watch.displayName = 'Watching assets'

let dev = gulp.series( build, gulp.parallel(server.start, watch) )
// dev.displayName = 'Starting local webserver'

let start = gulp.series( build, server.start )
// start.displayName = 'Starting local webserver'

let optimize = gulp.parallel( images.optimize, svgs.optimize )
// optimize.displayName = 'Optimizing assets'

/* Tâche par défaut est dev */
module.exports = {
    'default': dev,
    dev,
    start,
    build,
    optimize,
}
```

**Comment by phated** [comment]
DisplayName is the name of the task you run at the command line, so your usage was kind of wonky.

**Comment by mrleblanc101** [comment]
@phated I don't see what is wonky. DisplayName is used so the CLI show `Starting 'Building assets'...` instead of `Starting 'default'...`

**Comment by phated** [comment]
It's the name of the task registered in the task system. You are not using it in the correct way.

**Comment by sttk** [comment]
I mistook `.displayName` of https://github.com/gulpjs/gulp-cli/issues/223#issue-717742891 as `.description`.

`.displayName` is used to attach an alias of function name. See https://gulpjs.com/docs/en/api/task/

**Comment by mrleblanc101** [comment]
Thanks @phated @sttk 

I'll look into this. The name of the propriety is pretty confusing. `displayName` should be a name meant for displaying, not as a unique identifier.

I think we misused `.displayName` as the `.description`. What I don't like about the description is that it is not shown in the prompt (only when listing with `--task`

Here what our prompt looked like when we ran ou default Gulp task:

**Comment by contra** [comment]
@mrleblanc101 Wasn't our decision to name it that way - this is how JS named functions work https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName so we're just trying to stick to standard JS and not invent a new property name

**Comment by mrleblanc101** [comment]
I kept my multi word `displayName` for my function and removed it for my exported task and everything still look good. I just have a `Starting "default"...` at the beginning instead of my custom message, but it's still clean as it works for my function inside the default task. Thanks 

I think the issue is more that this is a regression because it worked in 2.1.0, but I understand we didn't use it properly so I'll close this issue. You can reopen if you think this should be fixed.

**Comment by mrleblanc101** [comment]
This was the only problem when upgrading all our devDependancy. Now that we made the small tweak of removing the displayName for the main task, we have upgraded to the lastest version of gulp-cli

**Comment by phated** [comment]
I'm glad you were able to work around it. 

> I think the issue is more that this is a regression because it worked in 2.1.0, but I understand we didn't use it properly so I'll close this issue. You can reopen if you think this should be fixed.

It's not a regression because you were actually relying on a bug in the way that code was implemented in relation to exports. The 2.2.0 release fixed that bug.

**Comment by Abror21** [comment]
Thanks
