### ISSUE TITLE
Find a bug of gulp command  and reason

### ISSUE THREAD

**Issue by HuTaoHub** [gulpjs/gulp-cli#242]
Using the gulp command error:
fileName: E:\blog\public\posts\d87f7e0c.html

  domainEmitter: [object Object]

  domainThrown: false

[20:11:00] 'default' errored after 12 s

I had found Error Reporting Reason: After troubleshooting, the reason is that the following occurs in the non code segment of the markdown document:

<0>or<1>or<2>or< any number> Format

<0,0>Format

A<0,0>format

For example__ default_ alloc_ Template<0, 0>will report an error

Preliminary solution:

`<0>`
`__ default_ alloc_ template<0, 0>`

Looking forward to a reply :)

**Comment by phated** [comment]
This is unrelated to gulp. It is an error emitted by one of your plugins.
