### ISSUE TITLE
gulp-cli does not pick up gulpfile.babel.js

### ISSUE THREAD

**Issue by ide** [gulpjs/gulp-cli#27]
(Moved from https://github.com/gulpjs/gulp/issues/1098)

The gulp program that comes with the gulp-cli package (0.2.0) doesn't find gulpfile.babel.js. Uninstalling gulp-cli and globally installing gulp fixed the problem so this isn't urgent, but it seems like gulp-cli should work.

**Comment by sonicbobcat85** [comment]
I second this.

**Comment by dcrockwell** [comment]
+1

**Comment by TomClarkson** [comment]
+2

**Comment by JZL003** [comment]
+3

It's also odd, it will work fine, I'll add a few node packages then it'll stop working. I'll remove and reinstall and it'll work fine. It's very odd to me

**Comment by dcrockwell** [comment]
I found the issue on my system:

* I had a system version of `node` installed, which had a globally installed `gulp` of an earlier version. It was linked to `/usr/local/bin/gulp`.
* I use `nvm` to manage different versions of `node` and `iojs`, but although I had gulp installed globally and locally in my projects, the paths for `/usr/local/bin` were of higher priority than my local paths.

The solution for me was:

1. `nvm use system`
2. `npm uninstall gulp -g`

**Comment by ide** [comment]
My setup doesn't have a system version of Node but good to eliminate that as a possible source of bugs.
```
$ nvm use system
System version of node not found.
$ which gulp
/Users/ide/.nvm/versions/io.js/v2.3.1/bin/gulp
```

**Comment by TomClarkson** [comment]
Thanks reinstalling gulp fixed it for me

**Comment by robabby** [comment]
@dcrockwell thanks for the recommendation, that worked for me.

**Comment by phated** [comment]
Fixed by https://github.com/gulpjs/gulp-cli/commit/dc5409639f1eabb70bb943981afba29024268288

**Comment by phated** [comment]
This should be fixed as of 0.3.0 (just published).  Please note that the .es6 extension that was supported in 0.2.0 was removed.  I will be rebasing these changes onto the 4.0 branch shortly.

**Comment by ripper2hl** [comment]
Same problem, this is fixed or not ? D: 
![captura de pantalla de 2015-07-23 10 42 19](https://cloud.githubusercontent.com/assets/2611201/8854827/91621ec2-3127-11e5-990d-732cb29fcd59.png)

**Comment by phated** [comment]
Please read your console output before posting. It states that you are using gulp 3.8.11 globally, which is completely the wrong version

**Comment by danjuz** [comment]
@dcrockwell solution worked fine for me to. Thank you!

**Comment by Theminijohn** [comment]
+1, reinstall Gulp worked for me!

**Comment by vyorkin** [comment]
guys, just curious, why do you ever need gulp.babel.js? you already using babel, so just use the [require hook](https://babeljs.io/docs/usage/require/). this is easy:
* `require('babel/register')` for babel 5.x
* `require('babel-core/register')` for babel 6.x
