### ISSUE TITLE
npm@3 extraneous packages

### ISSUE THREAD

**Issue by williamboman** [gulpjs/gulp-cli#30]
When using `npm@3` I get error logs about `gulp-cli` having extraneous packages.

Example;

```
npm ERR! extraneous: gulp-cli@0.3.0 /Users/MarkZuckerberg/.nvm/versions/node/v0.12.7/lib/node_modules/gulp-cli/node_modules/gulp-cli
```

Not sure if this happens due to `npm@3` or if `gulp-cli` installs a new version of itself by itself.

**Comment by phated** [comment]
I don't see any dependency that would cause gulp-cli 0.3.0 to install gulp-cli as a dependency of itself.  If anyone is able to test/debug this further, I'd love the help.

@williamboman side note: great username :stuck_out_tongue:

**Comment by phated** [comment]
@iarna @othiym23 any thoughts why this would happen?

**Comment by iarna** [comment]
Well, not knowing what command is being run makes this hard to know for certain, but I bet it was `npm update` which will be broken until the next release of npm@3 (next Thursday).

**Comment by williamboman** [comment]
`npm update -g`. I've gotten the error for other global packages like `npm` itself.

I'll close this here as it seems to be npm-related.
