### ISSUE TITLE
gulpInst is undefined

### ISSUE THREAD

**Issue by ibc** [gulpjs/gulp-cli#31]
```bash
~/src/foo $ gulp
[10:33:45] Using gulpfile ~/src/foo/gulpfile.js
/Users/ibc/.npm-packages/lib/node_modules/gulp-cli/index.js:133
    gulpInst.start.apply(gulpInst, toRun);
                  ^
TypeError: Cannot read property 'apply' of undefined
    at /Users/ibc/.npm-packages/lib/node_modules/gulp-cli/index.js:133:19
    at process._tickDomainCallback (node.js:381:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

```bash
~/src/foo $ gulp -v
[10:33:51] CLI version 0.1.3
[10:33:51] Local version 4.0.0-alpha.1
```

It also happens with latest `gulp-cli` 0.3.0 (`gulp-cli` is globally installed).

*NOTE:* Using local `gulp` 4.0.0-alpha.1 and global `gulp-cli` 0.1.3 worked fine until I upgraded `gulp-cli` to 0.3.0. Then the error above happended, but worse, once I reverted to `0.1.3` the problem **still** happens, so it may be due to an updated dependency within `gulp-cli` (just wondering).

**Comment by heikki** [comment]
`npm install -g "gulpjs/gulp-cli#4.0"` ?

**Comment by heikki** [comment]
Déjà vu.. https://github.com/gulpjs/gulp-cli/issues/9#issuecomment-69757010

**Comment by noelyahan** [comment]
Issue is now they don't have a branch called now they only maintain the master "gulpjs/gulp-cli#4.0". It can be solved by simply removing the old gulp-cli globally `npm remove -g gulp-cli` and reinstall it `npm install -g gulp-cli`. It will install the latest release tag which is `1.2.2`

**Comment by xiaofoyuan** [comment]
@noelyahan Thanks very good

**Comment by allawitte** [comment]
Everything what was described works good on Windows, but on Linux the issue was not solved. I manage to solve the problem when I decrease version of gulp to 3.9.1

**Comment by carlobeltrame** [comment]
@allawitte At first, `npm install -g gulp-cli` didn't work for me either, but closing and opening a new console, it worked.

**Comment by sekamdex** [comment]
As @carlobeltrame said, closing and opening a new terminal window did work for me!

**Comment by SvPhilip** [comment]
> Everything what was described works good on Windows, but on Linux the issue was not solved. I manage to solve the problem when I decrease version of gulp to 3.9.1

**I'm on Linux too.** Decreasing version of gulp to 3.9.1 **helped me** to execute task:
  gulp.task('scss', function(){
    return gulp.src('app/scss/**/*.scss')
        .pipe(sass({outputStyle : 'expanded'}))
        .pipe(gulp.dest('app/css'))
});  

**but when I try to execute task:** 

gulp.task('watch', function(){
    gulp.watch('app/scss/**/*.scss', gulp.parallel('scss'))
});
**it shows an error:**

Using gulpfile ~/gulp-start/gulpfile.js
[19:56:17] Starting 'watch'...
[19:56:17] 'watch' errored after 369 μs
[19:56:17] TypeError: gulp.parallel is not a function
    at Gulp.<anonymous> (/home/philip/gulp-start/gulpfile.js:11:43)
    at module.exports (/home/philip/gulp-start/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/philip/gulp-start/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/philip/gulp-start/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/philip/gulp-start/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/nodejs/gulp/bin/gulp.js:132:20
    at process._tickCallback (internal/process/next_tick.js:61:11)

Could someone help me with that? I spend the entire day to find a solution, but still can't figure out what to do.

**Comment by phated** [comment]
@SvPhilip issues are not the correct place to ask for support. We have https://github.com/gulpjs/gulp/discussions as the place for you to request support from the community.
