### ISSUE TITLE
Better error message when no local gulp exists

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#34]
Currently, when people don't have a local gulp installed, they are seeing errors such as #33 

I'd really like to have a better check around local gulp install and a nice error message.

@tkellen is there a way for us to do this using the object Liftoff gives us?

**Comment by tkellen** [comment]
I'm not able to reproduce this out of master or the 4.0 branch.

Both of these checks are functioning correctly for me:
https://github.com/gulpjs/gulp-cli/blob/master/index.js#L88-L95
https://github.com/gulpjs/gulp-cli/blob/4.0/index.js#L120-L127

**Comment by tkellen** [comment]
To clarify, I'm seeing this with the following:
```
npm uninstall -g gulp
npm uninstall -g gulp-cli
git clone git@github.com:gulpjs/gulp-cli.git
cd gulp-cli
npm link
cd ..
mkdir project
cd project
gulp
touch gulpfile.js
gulp
```

**Comment by tkellen** [comment]
As a point of clarification, I'm seeing this (correct) behavior on node 0.12 and node 4.0. I need a set of reproduction steps to help here.

**Comment by phated** [comment]
@tkellen I think the way you get it is by running `gulp -v` when no local module is installed.  Maybe the solution is to swap those 2 `if` blocks?

**Comment by tkellen** [comment]
I'm not seeing this with `gulp -v` either. This check is working correctly for both versions:
https://github.com/gulpjs/gulp-cli/blob/4.0/index.js#L97
https://github.com/gulpjs/gulp-cli/blob/master/index.js#L82

**Comment by phated** [comment]
hmm, maybe we need to check `env.modulePackage` as well on line https://github.com/gulpjs/gulp-cli/blob/4.0/index.js#L120?  It seems that liftoff finds the path, continues further until I pass the version to `findRange()`

Or maybe this problem just goes away when network drive stuff is fixed all the way down the stack :stuck_out_tongue:

**Comment by phated** [comment]
@tkellen I actually can't get this to happen either.  Now that the findup-sync problem has been resolved, I will probably close this.  I will leave it open for a little while longer incase anyone produces a repro case.

**Comment by phated** [comment]
Going to close this
