### ISSUE TITLE
Support recursive tree output for --tasks

### ISSUE THREAD

**Issue by sandipchitale** [gulpjs/gulp-cli#35]
Something like:
```javascript
        function printTaskTree(tasks, taskKey, indent) {
		    var taskObject;
		    taskObject = tasks[taskKey];
		    if (taskObject) {
		        console.log(indent + (taskObject.name ? taskObject.name : taskKey));
		        if (taskObject.dep) {
		            taskObject.dep.forEach(function(name) {
		                printTaskTree(tasks, name, indent + '  ');
		            });
		        }
		    }
		}

        printTaskTree(gulp.tasks, 'default', '');
```

**Comment by contra** [comment]
Send a PR?

**Comment by phated** [comment]
This can be done in userland with the exposed `gulp.tree()` method.  Not likely to add this to the CLI

**Comment by phated** [comment]
As per https://github.com/gulpjs/gulp-cli/pull/36#issuecomment-142103723, undertaker builds the recursive tree, it shouldn't be the responsibility of the `taskTree` method to do that.

**Comment by phated** [comment]
The test has been updated to be less confusing in https://github.com/gulpjs/gulp-cli/commit/1c0da0d35a81ac1a0e0e4e3296026bd06cd43d12
