### ISSUE TITLE
document CLI options

### ISSUE THREAD

**Issue by terinjokes** [gulpjs/gulp-cli#38]
The CLI options aren't currently documented, and it's not clear, even when looking at the source, what the options are.

**Comment by phated** [comment]
We have support for --help now but I can stick the output of that in the readme

**Comment by contra** [comment]
@phated Something left to document? Closed this because github didn't autoclose it even though you put "closes #38" in the commit

**Comment by phated** [comment]
Not happy with the formatting. They are still in a branch while I work on them. Sorry

**Comment by contra** [comment]
np misunderstood

**Comment by phated** [comment]
@terinjokes can you review the docs in https://github.com/gulpjs/gulp-cli/tree/docs

**Comment by phated** [comment]
Merged to 4.0
