### ISSUE TITLE
support documenting and displaying task flags

### ISSUE THREAD

**Issue by chmontgomery** [gulpjs/gulp-cli#39]
This request came out of this discussion: https://github.com/chmontgomery/gulp-help/pull/19

In gulp4 it would be nice to allow documenting task flags. I am already making this possible via [`gulp-help`](https://github.com/chmontgomery/gulp-help/tree/gulp4), along with a few other features as seen here:

<img width="605" alt="screen shot 2015-09-28 at 3 36 30 am" src="https://cloud.githubusercontent.com/assets/232356/10131147/d001ba98-6593-11e5-8d60-1fbd085ada4b.png">

The suggestion was brought up to possibly add this feature to gulp core. I'd be willing to help with a PR but I'm curious what your thoughts are on doing this and how best to design it.

Also, I think neither current task view (`--tasks` or `--tasks-simple`) displays in a way conducive to showing task flags. I'd suggest a new flag, perhaps `--tasks-pretty` that looks closer to what I have above?

**Comment by phated** [comment]
We currently support description on task functions but I don't think we are going to add some custom API to specify flags that those functions look for.  I know @contra reached out on that issue but I think he missed what is actually happening in the screenshot.

**Comment by phated** [comment]
Note: with the separation of the CLI, these things can/should be done as a custom CLI

**Comment by contra** [comment]
@phated No, I saw what was happening in the screenshot. There are enough people who want custom shit displayed in the CLI that we should make it flexible enough for people to do custom lenses powered by undertaker metadata

**Comment by phated** [comment]
I think we could add this add an `options` property to the function (similar to how descriptions work) and then print them in the CLI.  However, the current design doesn't support that at all.  Before this feature would be implemented, I need to see some mockups of a new tasks display output.  It must cover: listing top level tasks, listing dependencies of the tasks (nested to all levels of the hierarchy), the description and the options.  If someone produces a good mock that can display all of those things in a non-confusing manner, I think we can add this.  @chmontgomery would you be willing to produce a mockup?

**Comment by phated** [comment]
Also opened a request on the main gulp repo for mockups

**Comment by chmontgomery** [comment]
@phated my personal opinion is that displaying the dependency tree, descriptions, and flags all in one output would be messy. With all the lines, it would be difficult to distinguish between flags and tree dependency lines. The dependency tree is super helpful, but perhaps as an ancillary option? I would suggest a task listing flag that only lists:

1. Display top level tasks prominently
1. Display the description next to each top level task
1. Display a list of flags for each top level task

so essentially, the screenshot I already have above. Thoughts?

**Comment by phated** [comment]
@chmontgomery unfortunately, the task dependency tree is mandatory.  There are too many reports from people not understanding how their dependency tree is formed and running, and with the addition of function composition through `series` and `parallel` methods, the mental overhead to visualize the dependency tree gets even more complex.  So we must show that in the main task listing command.

**Comment by chmontgomery** [comment]
@phated that makes sense. What about this idea: going back to @contra's point, what if we provide a configuration point (via `gulpfile.js` or something else) that allows someone to provide their own custom function for displaying tasks? This would allow for anyone's crazy way of displaying help. I could easily port my help styles to be used in that way.

If you want we can put it behind a separate flag so as to keep your dep tree under `--tasks`. e.g. `--tasks-help`, `--tasks-custom`, `--tasks-info`, etc.

**Comment by phated** [comment]
@chmontgomery There's definitely a bunch of ways to tackle an API that supports this.  I don't want to add any more API surface area to the `gulp` namespace, but attaching things to the task functions is pretty open.  I'd really like to solve this with the main `--tasks` flag if we can come up with a sensible UI for it but if not, maybe it can hide behind a different flag.  Still need some time to think over how this will shake out.

**Comment by chmontgomery** [comment]
@phated one more idea: what if we leave the `--tasks` flag as is (to accomplish your point) but allow it to be overridden given a custom function. That way we're not adding more surface area, leaving a sensible default but also allowing the user to overide and customize the view however they wish (including new flags, aliases, etc).

**Comment by Xiphe** [comment]
I'm really interested in this, too. 
Main points for me:
 - hide helper tasks, that are not meant to be executed by a user
 - display cli/env options

**Comment by phated** [comment]
@Xiphe the first point is already supported in gulp 4 by just using plain functions instead of registering them as tasks with gulp.  The linked issue in the main gulp repo is looking for UI mockups to support the 2nd.

**Comment by Xiphe** [comment]
:+1: thanks

**Comment by phated** [comment]
Due to an great design by @tylersticka and amazing work by @sttk - we now support this in gulp-cli v1.2.0

You can find the docs at https://github.com/gulpjs/gulp-cli#custom-metadata

**Comment by Xiphe** [comment]
love it!

**Comment by simonua** [comment]
User error, I'm sure, but I can't seem to get this to work right. Could you please shed some light on what I am doing wrong? Thank you and thanks for getting this feature added to the CLI!

    var gulp = require('gulp');
    
    gulp.task('cat', function cat(done) {
        cat.description = 'I am a cat.'
        cat.flags = {
            '--makeNoise': 'Instruct me to meow occasionally.'        
        };
        
        done();
    });

![task description and flags](https://cloud.githubusercontent.com/assets/8005145/12752278/c0590686-c98f-11e5-898d-7b781732cbc9.png)

**Comment by sttk** [comment]
@simonua Thank you for the check.

The function `cat` is not set its `description` and `flags` unless it is executed.

You can show the description and flags by the code below:
```js
var gulp = require('gulp');
                                                                                
gulp.task('cat', cat);

function cat(done) {
    cat.description = 'I am a cat.'
    cat.flags = {
        '--makeNoise': 'Instruct me to meow occasionally.'        
    };

    done();
}

cat(function(){});
```

**Comment by simonua** [comment]
@sttk Thank you for clarifying. The syntax for the function makes sense to me now and aligns with the CLI documentation. It wasn't intuitive to me to invoke the function, so thank you for pointing that out. Did I just miss this completely in the CLI documentation or is it not there?

**Comment by simonua** [comment]
Also, and this may be irrelevant, but I see symbols in front of the description property. I tried this in a regular Windows console and ConEmu. I used your code.

![task list console issue](https://cloud.githubusercontent.com/assets/8005145/12763367/02fe6a94-c9c2-11e5-9bd2-b805a0a5efe5.png)

**Comment by phated** [comment]
Don't set the properties inside the function. Just assign them to the function after definition. Yes, the ... is part of the design.

**Comment by simonua** [comment]
@phated Thank you. That allowed me to drop the function invocation, making this a bit more intuitive and natural IMHO. @sttk Nice touch on ordering the flags in the output for `gulp -T` even though I did not order them in my object. +1 for UX. 

    var gulp = require('gulp');
    
    gulp.task('cat', cat);
    gulp.task('dog', dog);
    
    function cat(done) {
        done();
    }
    
    function dog(done) {
        done();
    }
    
    //Properties for gulp-cli 1.2 task listing.
    cat.description = 'I am a cat.';
    cat.flags = {
        '--makeNoise': 'Meow occasionally.',
        '--eatFood': 'Eat food.'
    }
    
    dog.description = 'I am a dog.';
    dog.flags = {
        '--makeNoise': 'Bark constantly.',
        '--comeWhenCalled': 'Be responsive.'
    }

![multiple tasks with description and multiple flags](https://cloud.githubusercontent.com/assets/8005145/12764422/a986cf32-c9c7-11e5-87f1-d008cdca75e1.png)

**Comment by Xiphe** [comment]
to avoid misunderstandings, this is how the function should be decorated:

```js
var gulp = require('gulp');

gulp.task('cat', cat);

function cat(done) {
   /* meow */
    done();
}
cat.description = 'I am a cat.';
cat.flags = {
    '--makeNoise': 'Instruct me to meow occasionally.'
};
```

**Comment by sttk** [comment]
And this way is also OK for no name function.

```js
gulp.task('cat', function(done) {
  done();
});
gulp.task('cat').description = 'I am a cat.'
gulp.task('cat').flags = {
  '--makeNoise': 'Instruct me to meow occationally.'
};
```

**Comment by simonua** [comment]
@sttk, @phated, @Xiphe Thank you / Vielen Dank! I appreciate the insight and got the answers I needed. I'm sorry to piggy-back on this "issue" with implementation questions as there may have been more appropriate places to do that. It may be beneficial to carry some of these examples or info back into the gulp-cli 1.2.0 documentation if you feel it would make it clearer. Either way, thanks again!

**Comment by phated** [comment]
Added a full usage example in the [custom-metadata](https://github.com/gulpjs/gulp-cli#custom-metadata) section.  Going to lock this so it doesn't gain extra noise (the last few comments should have cleared up any confusion).  Thanks everyone.
