### ISSUE TITLE
tasks should be able to delay timeout

### ISSUE THREAD

**Issue by terinjokes** [gulpjs/gulp-cli#40]
Tasks should be able to delay the timeout notification, as they are based able to determine if intensive work is being done. Otherwise, gulp-cli cascades the "Task did not complete after 10s." notification for everything in-flight, which in my case could include a number of orchestration tasks ("default", "series', "parallel", then finally the two tasks that are hard at work and eventually complete)

**Comment by contra** [comment]
Kind of similar to what mocha does

**Comment by phated** [comment]
The timeout feature is just a debugging tool for people that are writing bad gulpfiles (there seems to be a lot of that happening).  It doesn't fail the task or exit or anything like that.  When running the gulpfile normally, set the timeout to 0.   Maybe we need to default it to 0, but I feel like people will lose the benefit of it if off by default.

**Comment by phated** [comment]
I am not going to add API surface to the gulp core API to programmatically control this.

**Comment by phated** [comment]
With the newly proposed implemenation in https://github.com/gulpjs/gulp/issues/1268, I am 100% sure this is not needed.  Closing.
