### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#49]
Would love to have a legit change log.  I'll even attach to each version in "Releases".  Anyone want to take a stab based on the commits?

**Comment by Xiphe** [comment]
I recently fell in love with [semantic-release](https://github.com/semantic-release/semantic-release).

They write the changelog into the [github releases view](https://github.com/gulpjs/gulp-cli/releases) which is even better than an `changelog.md` file imo.
They use the [AngularJS Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit) but we could also implement a different style.

If you'd rather continue like to release manually i could also look into that. Do you simply want to list the commits between two tags, or do you have anything specific in mind here?

See [semantic-release releases](https://github.com/semantic-release/semantic-release/releases) for an example

**Comment by contra** [comment]
We should copy the same thing we use for vinyl/vinyl-fs
