### ISSUE TITLE
Hook up to travis and appveyor

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#5]
Needs to be done by @contra

**Comment by heikki** [comment]
Can we have a gulpjs account on appveyor? 
Currently builds point to here -> https://ci.appveyor.com/project/phated/gulp-cli

- http://help.appveyor.com/discussions/questions/910-how-to-create-an-account-for-a-github-org
- http://help.appveyor.com/discussions/questions/744-using-appveyor-for-a-github-org

**Comment by heikki** [comment]
I created new one -> https://ci.appveyor.com/project/gulpjs/gulp-cli
