### ISSUE TITLE
4.0 branch for gulp 4.0?

### ISSUE THREAD

**Issue by metalim** [gulpjs/gulp-cli#55]
Does it really matter which branch of gulp-cli do I use with gulpjs/gulp#4.0 ?

4.0 branch has version number 0.4.0 and libs for gulp 4.0 alpha 1 and 2
master branch has version number 1.1.0 and libs for gulp 4.0 alpha 1, 2 and release.

Is branch 4.0 redundant now?

**Comment by phated** [comment]
Yeah, you should be using the published version. I left the branch around in case people had it as a dependency. I will clean it up at some point. I'll leave this open until then.

**Comment by phated** [comment]
Finally deleted these after much confusion by people.
