### ISSUE TITLE
Apply --depth flag to --tasks-json flag output

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#57]
In 1.2.0, @sttk added a `--depth` flag to gulp-cli; However, we didn't apply it to the `--tasks-json` flag to reduce the exponential growth as described in https://github.com/gulpjs/gulp/issues/1033

@sttk If you or anyone else would like to expand on the functionality you added for `--depth` and apply it to `--tasks-json`, that would be super helpful.

**Comment by sttk** [comment]
@phated I'm willing to tackle this also, but I have a question.

There are cases that `--depth` cuts child tasks of series/parallel tasks. Are the json data of such series/parallel tasks useful? 

I think `--tasks-json` should be able to output in two type forms, a full tree and a tree until first child tasks which are not series/parallel tasks. And the latter form would be possible if gulp-cli can get `branch` flags in undertaker.

**Comment by sttk** [comment]
However, it may be better that `--tasks` and `--tasks-json` can output same trees by `--depth`. How do you think about my idea below?

```js
(default or --depth=full)
[07:09:11] ├─┬ task0
[07:09:11] │ └─┬ <series>
[07:09:11] │   ├─┬ <parallel>
[07:09:11] │   │ ├── func1
[07:09:11] │   │ └── func2
[07:09:11] │   └── func3
[07:09:11] └─┬ task1
[07:09:11]   └─┬ <series>
[07:09:11]     └─┬ task0
[07:09:11]       └─┬ <series>
[07:09:11]         ├─┬ <parallel>
[07:09:11]         │ ├── func1
[07:09:11]         │ └── func2
[07:09:11]         └── func3
```
```js
(--depth=3)
[07:10:10] ├─┬ task0
[07:10:10] │ └─┬ <series>
[07:10:10] │   ├── <parallel>
[07:10:10] │   └── func3
[07:10:10] └─┬ task1
[07:10:10]   └─┬ <series>
[07:10:10]     └── task0

(--depth=4)
[07:11:37] ├─┬ task0
[07:11:37] │ └─┬ <series>
[07:11:37] │   ├─┬ <parallel>
[07:11:37] │   │ ├── func1
[07:11:37] │   │ └── func2
[07:11:37] │   └── func3
[07:11:37] └─┬ task1
[07:11:37]   └─┬ <series>
[07:11:37]     └─┬ task0
[07:11:37]       └── <series>
```
```js
(--depth=nonrecursive, or another name. I didn't find an appropriate name.) 
[07:11:37] ├─┬ task0
[07:11:37] │ └─┬ <series>
[07:11:37] │   ├─┬ <parallel>
[07:11:37] │   │ ├── func1
[07:11:37] │   │ └── func2
[07:11:37] │   └── func3
[07:11:37] └─┬ task1
[07:11:37]   └─┬ <series>
[07:11:37]     └── task0
```

**Comment by phated** [comment]
@sttk thanks for working on this.  All the information I have is at https://github.com/gulpjs/gulp/issues/1033 - I'll cc @segrey here to give more insights on how he needs this to be for IDE integration.  Thanks again.

**Comment by sttk** [comment]
First, I've modified that `--tasks-json` outputs same trees as current `--tasks` using `--depth` flag.

[sttk/gulp-cli#modify_for_tasks_json](https://github.com/gulpjs/gulp-cli/compare/master...sttk:modify_for_tasks_json)

Modifications:
  * `copyTree` was separated from `logTasks` except sorting tasks and node creations.
  * changed the processing for `--tasks-json` in each `index.js` of the versions to use `copyTree` and to support `--depth` flag.
  * added tests for `copyTree`.
  * added a test case to `taskTree.js`. This case shoud have been added at the time of the modification for `--tasks`.

**Comment by sttk** [comment]
In addition, I've added modifications to support `--depth=nonrecursive`.

[sttk/gulp-cli#modify_for_tasks_json_norcr](https://github.com/sttk/gulp-cli/compare/modify_for_tasks_json...sttk:modify_for_tasks_json_norcr)

But this program identifies series/parallel tasks by their labels `<series>` or `<parallel>` tentatively. For this I want to modify **undertaker** to include `branch` flags in its task tree output. Can I do it?

**Comment by phated** [comment]
@sttk at first thought, that should be fine.

**Comment by segrey** [comment]
@sttk thanks for working on this. Seems `--depth=nonrecursive` does exactly what's needed. As for naming, maybe `--depth=compact`?

**Comment by sttk** [comment]
Thank you for replies.

@phated Please tell me problems you think about my second thought above.

@segrey I've changed the naming of `--depth=nonrecursive` to `--depth=compact`.

**Comment by phated** [comment]
@sttk does it make sense to just make everything non-recursive and change the color or use some other indicator (maybe @tylersticka could help us brainstorm that design).  There are a few issues, including #1410 and #1033, that mention this problem.  Also, I don't really like making a numerical flag take some other value.

**Comment by tylersticka** [comment]
Boy, this is a tough problem to solve! I'm using @phated's [example from the other issue](https://github.com/gulpjs/gulp/issues/1033#issuecomment-94957927) as a point of reference.

I initially took @phated's suggestion and tried playing with color, but the issue is that if you have two `gulp.series` or `gulp.parallel` groups one right after the other, there's no way to differentiate where one group stops and the other ends. Also, the child tasks end up kind of overpowering anything else... I really like the look of cool colors like cyan and purple for task names and such, but they are overthrown easily by any warmer colors in the palette.

My next experiment was a play with what @sttk recommended. The only changes are that I like parentheses more than less-than/greater-than signs (there are already so many hard angles in this output), and I started playing with different [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) to differentiate parallel tasks from series:

![screen shot 2016-02-08 at 4 24 03 pm](https://cloud.githubusercontent.com/assets/69633/12904125/dd71da44-ce81-11e5-88fb-1e3749393885.png)

```
[18:08:06] └─┬ combined      Build all the things!
[18:08:06]   │ --dev         …un-minified
[18:08:06]   │ --production  …compressed into single bundle
[18:08:06]   ├── clean
[18:08:06]   ├─╥ (parallel)
[18:08:06]   │ ╟── js
[18:08:06]   │ ╟── css
[18:08:06]   │ ╙── img
[18:08:06]   └─┬ (series)
[18:08:06]     ├── some
[18:08:06]     ├── other
[18:08:06]     └─╥ (parallel)
[18:08:06]       ╟── thing
[18:08:06]       ╙── stuff
```

This works fine, though I'm not sure the different drawing characters are communicating very much... the headings say everything on their own, really.

Then I wondered if maybe I could eliminate those `(parallel)` and `(series)` headings entirely, retaining the indentation and pushing the parallel line characters further:

![screen shot 2016-02-08 at 4 33 14 pm](https://cloud.githubusercontent.com/assets/69633/12904147/099038fa-ce82-11e5-969e-3f117c05a437.png)

```
[18:08:06] └─┬ combined      Build all the things!
[18:08:06]   │ --dev         …un-minified
[18:08:06]   │ --production  …compressed into single bundle
[18:08:06]   ├── clean
[18:08:06]   ╞═╦══ js
[18:08:06]   │ ╠══ css
[18:08:06]   │ ╚══ img
[18:08:06]   └─┬── some
[18:08:06]     ├── other
[18:08:06]     ╘═╦══ thing
[18:08:06]       ╚══ stuff
```

I like the way this _looks_ more, but it may be harder to read... I can't tell if it's clear what the series versus parallel groupings are. Would love to get some more opinions.

**Comment by phated** [comment]
It's not too clear what the parallel and series tasks are.  Maybe `(series)` or `(parallel)` could come after the top level task name?  e.g. `build (series)`

**Comment by sttk** [comment]
@phated ...I might misunderstand "at first thought" in your saying.

I received your saying that first thought, which is to apply current `--depth` flag, was fine (but second thought, which is to add `--depth=non-recursive`, was not fine). Was that meaning like "at first glance" or "at first sight"? (Or didn't I misunderstand? You said "I don't really like ...".)

...Sorry. My english skill is poor.

**Comment by sttk** [comment]
Should I send a PR of  #modify_for_tasks_json, or add a new option for non-recursive?

**Comment by phated** [comment]
@sttk sorry, I meant surfacing the branch flag would be fine.  I'd like to figure out if we can make "non-recursive" the default and only behavior before we go about adding it as part of the flag.  If we can communicate everything concisely in the `--tasks` UI in a non-recursive manner, I'm okay with making that the only way things are displayed.

**Comment by segrey** [comment]
@phated I think it makes sense to have the only behavior. Alternative idea could be to have `--tasks-json=top` (without dependencies of top level tasks) and `--tasks-json=full` (the same as `non-recursive`). The same can be applied for `--tasks`.

**Comment by phated** [comment]
@segrey `--tasks-json` already takes a path argument to output to the filesystem.  I don't want to overload the flags.

**Comment by segrey** [comment]
@phated Oops, sure. Then it can be `--depth=top`, `--depth=full`.

**Comment by phated** [comment]
@segrey depth is currently a number and I think the number makes more sense because you can specify the depth you are looking for.

**Comment by segrey** [comment]
@phated I'm okay with current behavior (when depth is a numerical flag). IIUC, you'd like to not mix number and string values (e.g. `--depth=1` and `--depth=non-recursive`). FWIW, an alternative option could be to have string values only.

**Comment by tylersticka** [comment]
> It's not too clear what the parallel and series tasks are. Maybe (series) or (parallel) could come after the top level task name? e.g. build (series)

Hmm... I don't love that idea because I'm not sure how it would scale to series or parallel tasks that _follow_ a series or parallel task. Would it concatenate, saying `build (series) (series)`?

Here's a simpler idea... restoring the cyan coloring to child tasks, but retaining the gray for the `series` and `parallel` headings:

![screen shot 2016-02-09 at 2 57 10 pm](https://cloud.githubusercontent.com/assets/69633/12933587/bf1307e6-cf3d-11e5-85cd-540046a07b84.png)

**Comment by phated** [comment]
@tylersticka The output for the above doesn't seem correct.  "combined" has 3 children - "clean", "parallel" and "series" but no indicator of how those children are executing.

I think the 2 things that need to be tackled are:
1. parallel and series clutter the task listing but have crucial information on how things are executing - this is the one you are currently mocking up
2. If a child task is used in another dependency tree, the entire child tree is duplicated in the output - suggestions for solving this include a color or some other indicator of a duplicate

**Comment by tylersticka** [comment]
Thanks, @phated !

> The output for the above doesn't seem correct. "combined" has 3 children - "clean", "parallel" and "series" but no indicator of how those children are executing.

You're right, there would be a "series" heading at the beginning based on [what I was referencing](https://github.com/gulpjs/gulp/issues/1033#issuecomment-94957927). Your suggestion makes more sense to me now.

> If a child task is used in another dependency tree, the entire child tree is duplicated in the output - suggestions for solving this include a color or some other indicator of a duplicate

Can you provide an example for me (or link to a pre-existing one in this thread)? I'm sure you're explaining it accurately but I feel like I'm still not understanding completely.

(And if at any point my mockups are complicating more than illuminating things, just let me know! I promise I won't take offense. :smile: )

**Comment by phated** [comment]
@tylersticka np, I am really happy to have someone with an eye for design helping on these problems.  The best place to look for an example is the base issue at https://github.com/gulpjs/gulp/issues/1033 - it shows how the output grows exponentially for some given gulpfiles

**Comment by tylersticka** [comment]
@phated Just read through gulpjs/gulp#1033 again. It's a bit difficult for me to parse, but it _sounds_ to me like what we'd like to do is visualize when a task is being called _repeatedly_ within the same task... so if task `a3` calls task `a1` and `a2`, but task `a2` _already_ calls `a1`, we would highlight that duplicate.

If that's the case, I feel like coloring the duplicate tasks _red_ would not be too strong. I'm sure my Gulp usage is less complicated than average, but if I accidentally had a task called multiple times I'd certainly want it visualized in a strong way.

An example:

![screen shot 2016-02-09 at 4 04 43 pm](https://cloud.githubusercontent.com/assets/69633/12934975/44cd5bf8-cf47-11e5-8acd-cb33305655f1.png)

I may have misread or only partially-understood the design ask here, so feel free to course-correct me.

**Comment by sttk** [comment]
@phate Sorry, and thanks about `branch` flag.

I'm also happy to communicate with you guys. (There are time differences among us, though.)

**Comment by sttk** [comment]
I think good to add a new option like `--tasks-xxx` for this "non-recursive". 
"non-recursive" could put at the same level as `--tasks` and `--tasks-simple`.

**Comment by sttk** [comment]
About option adding or naming, I think we should consider the option of unsorting top tasks together, which is proposed by @erikkemperman in #50. This helps users to check and comprehend tasks just as they wrote.

I intended to add an option value `--tasks=unsort` for this, because sorting top tasks is not needed for `--tasks-json`.

**Comment by sttk** [comment]
Oops, `--tasks-xxx` above is only for displaying.

And `--tasks-json` may have only to support "non-recursive".

**Comment by sttk** [comment]
(Sorry for continuing my posts.)

I created [a sample program](https://github.com/sttk/samples_for_gulp-cli/tree/hide_branch_tasks) to hide series/parallel tasks in outputs of `--tasks`. (But I don't think that hiding is better, though.)

```
> node tasksTest

Tasks (Not hide branch tasks)
├─┬ task0
│ └─┬ <series>
│   ├─┬ <parallel>
│   │ ├─┬ <series>
│   │ │ ├── task2
│   │ │ ├─┬ <palallel>
│   │ │ │ ├── task8
│   │ │ │ └── task9
│   │ │ └── task3
│   │ ├── task4
│   │ └── task6
│   └── task7
└── task1

Tasks (Hide branch tasks)
├─┬ task0
│ └─┬─┬─┬── task2
│   │ │ ├─┬── task8
│   │ │ │ └── task9
│   │ │ └── task3
│   │ ├── task4
│   │ └── task6
│   └── task7
└── task1
```

**Comment by sttk** [comment]
I've reflected the addition of `branch` flag by gulpjs/undertaker#60 and separated `compact` (non-recursive) option from `depth` option in my repository:

[sttk/gulp-cli#modify_for_tasks_json_norcr](https://github.com/sttk/gulp-cli/compare/modify_for_tasks_json...sttk:modify_for_tasks_json_norcr)

**Comment by phated** [comment]
@sttk is this worth sending as a PR or are you planning to make some more changes?

**Comment by sttk** [comment]
@phated I have no more changes. I've send the PR about this issue.
