### ISSUE TITLE
function.displayName support in exports caused a common case to break 

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#59]
The common case is `export const dist = series(clean, css);` which is broken because series/parallel get displayName attached.  Ref https://github.com/gulpjs/gulp-cli/commit/b7da669f8e9454f6b27da8afada04392797ef396#commitcomment-15987378

**Comment by phated** [comment]
Reverted and fixed by https://github.com/gulpjs/gulp-cli/commit/0af0e01f3e605f86b77e1f7909a709e16be38796 and regression test added.

**Comment by phated** [comment]
Published as 1.2.1

**Comment by CodeTheory** [comment]
Thanks for fixing this! :smile:

**Comment by phated** [comment]
No problem.  Wanted to track it in an issue too.
