### ISSUE TITLE
Reference to completion readme

### ISSUE THREAD

**Issue by axvm** [gulpjs/gulp-cli#66]
It would be nice if gulp-cli/readme will contain reference to [completion readme](https://github.com/gulpjs/gulp-cli/blob/master/completion/README.md)

Might be useful for everyone.

**Comment by Romanx** [comment]
I wasn't aware that was a thing so :+1: from me

**Comment by phated** [comment]
@avxm that doc should actually be moved here. Can you send a PR?

**Comment by axvm** [comment]
@phated sure
