### ISSUE TITLE
Implement .gulprc support

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#69]
Implement through use of https://github.com/js-cli/js-liftoff/issues/8 which has outstanding PR at https://github.com/js-cli/js-liftoff/pull/67

**Comment by phated** [comment]
Support for this in Liftoff was just published as 2.3.0

@sttk would you like to implement it for gulp?

**Comment by sttk** [comment]
@phated Yes, I'd like to implement it. 

I want to use key chain style for gulprc as below, but it is not popular as a configuration file. Can I use this style and the module [customerizer](https://github.com/sttk/customizer.git) for this?                                       

```js
cli.flags.cwd = 'path/of/cwd';
cli.flags.logLevel = 4; 

colors.tasks.tree.task.name = s => chalk.bold(chalk.blue(s));
colors.tasks.tree.task.description = chalk.black;
```

**Comment by phated** [comment]
@sttk I don't think the configuration file needs to be that complex.  I also think that attempting the implementation with the most simple thing first is the correct approach (so don't start with colors).  I think the easiest thing to support would be a top level `description` property as outlined in #70.  The `.gulprc` would then look like:
```json
{
  "description": "My sample description for gulpfile"
}
```
It could also be a node module that used `module.exports = ...` because we will just be using `require` to load the file.

**Comment by sttk** [comment]
@phated I got it. And I agree that we should start with the most simple configuration.

> ... we will just be using `require` to load the file.

`require` and `rechoir` can't get the extension `"rc"` from filename `".gulprc"`. So they loads the file as a js file.

For autoloading `.gulprc` with `rechoir`, we need to do follwing two things:

1. Create a new loader for JSON file. This code would do a thing like `module.exports = JSON.parse(fs.readFileSync(fp, opts))` and something similar to [module.load](https://github.com/nodejs/node/blob/master/lib/module.js#L449) except resolving extension.

2. Change `extension` module in `rechoir` to enable to get the extension `"rc"` from the filename `".gulprc"`. This would be made possible by seeking a matching tail in `rechoir`'s argument `config`.

**Comment by sttk** [comment]
@phated Can I change `rechoir` as above?

**Comment by phated** [comment]
Oh, you are right that `.gulprc` won't work out of the box with require. Let's just support `.gulp.js`, etc (all the extensions we already support).

**Comment by sttk** [comment]
I got it. I'll implement so.

**Comment by sttk** [comment]
@phated I determined that the configuration file name is `.gulprc.*`, and I'm planning the following features about the configuration file.

- [ ] Load and merge configuration files in home directory, project directory, current work directory if exists.
- [ ] Print configurations in JSON format by `--output-config` flag.
- [ ] Load and merge configuration files by `--config` or `-c` flag.
- [ ] Ignore configuration files by `--ignore-config` flag, except files specified by `--config` flag.

**Comment by sttk** [comment]
And I implemented the first and second check items in my repository.

[sttk/gulp-cli#support_gulprc](https://github.com/sttk/gulp-cli/tree/support_gulprc) ( [Comparing changes](https://github.com/gulpjs/gulp-cli/compare/master...sttk:support_gulprc) )

Please point out about the features, the implementations, etc.

**Comment by sttk** [comment]
@phated I've implemented all features above.

**Comment by phated** [comment]
@sttk please submit a PR, I think some of the stuff might be added complexity but I'd like to see it all together first.

**Comment by sttk** [comment]
@phated I've sended the PR #90 about this issue.
