### ISSUE TITLE
Support flags as options in .gulprc file

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp-cli#71]
The flags should be able to be defaulted in the .gulprc file so people can rely on gulpfiles running in a certain way.  e.g. running with a certain log level

**Comment by phated** [comment]
@sttk if you plan to implement more features in `.gulp.*`, start with this one before attempting #57 or #63

**Comment by sttk** [comment]
@phated Since the configs are merged with `opts`, the flags are already able to be configured with `.gulp.*` files. 

But those values aren't checked at all. Are the checks needed and are there any flags forbidden to configure with `.gulp.*` files?

**Comment by phated** [comment]
@sttk oh, I don't think that's the way I wanted it to work.  `flags` should be a property that gets merged into the flag options.  How should we handle this?

**Comment by phated** [comment]
Basic support for this was completed by #92 
@sttk does that PR add support for every flag or just the ones specified?  If it only supports a subset, should we leave this open?

**Comment by sttk** [comment]
@phated I think #92 is for creating mechanism to support flags.
We may add other flags or configs later as needs or requests.
So this issue might be closed.

**Comment by sttk** [comment]
@phated Or are there any flags what you are already thinking that we should add?
I'll implement to support those flags if you list them.

**Comment by phated** [comment]
I think I've opened issues for the 3 remaining flags that make sense as config options.  See #108 #109 and #110
