### ISSUE TITLE
--tasks-json is broken when using Gulp 3.9.1

### ISSUE THREAD

**Issue by james-nash** [gulpjs/gulp-cli#85]
Since switching to `gulp-cli`, I've noticed that the `--tasks-json` switch no longer works on projects that use 3.9.x versions of gulp.

### Expected result
Running `gulp --tasks-json` outputs a list of the tasks in JSON format.

### Observed result
Running `gulp --tasks-json` just starts the default tasks (as if the `--tasks-json` was not there)

### Steps to reproduce
1. Install `gulp-cli` on your system (I'm using version 1.2.1).
1. Navigate to the root of a project that has a Gulp 3.9.1 release locally installed
1. Run `gulp --tasks-json`

### Additional notes
This has the unfortunate effect of breaking the WebStorm IDE's Gulp tool window (which appears to use that switch to get a list of tasks). :-(

I've peaked at the `gulp-cli` code and noticed that the `lib/versioned/^3.7.0/index.js` does not appear to check for the `opts.tasksJson` inside `process.nextTick()`, whereas the corresponding `lib/versioned/^4.0.0/index.js` does.

Perhaps it's a simple omission and the code to enable the `--tasks-json` needs to be added to the ^3.7.0 file?

**Comment by phated** [comment]
As noted in the documentation, not all flags are supported. The orchestrator code base is a mess and I don't know of a way to get a task listing from it. Feel free to submit a PR if you can figure it out.
