### ISSUE TITLE
gulp-cli fails if local gulp is 4.0

### ISSUE THREAD

**Issue by ibc** [gulpjs/gulp-cli#9]
Within my project's `package.json` I have:

```
json
"dependencies": {
  "gulp": "git+https://github.com/gulpjs/gulp.git#4.0"
}
```

If I globally install stable `gulp` (3.X) and run `gulp` it fails (known issue, ok). But if I globally install `gulp-cli` it also fails:

```
bash
$ gulp
[15:59:34] Using gulpfile ~/src/XXX/gulpfile.js

/Users/xxxxxx/.npm-packages/lib/node_modules/gulp-cli/index.js:133
    gulpInst.start.apply(gulpInst, toRun);
                   ^
TypeError: Cannot call method 'apply' of undefined
    at /Users/xxxxxx/.npm-packages/lib/node_modules/gulp-cli/index.js:133:20
    at process._tickDomainCallback (node.js:463:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

I fail to understand the purpose of `gulp-cli` if it fails in this scenario. Do I miss something?

**Comment by heikki** [comment]
`npm install -g "gulpjs/gulp-cli#4.0` ?

**Comment by ibc** [comment]
OK, it works if I globally install gulp-cli 4.0 branch. However, shouldn't a simple `npm install -g gulp-cli` work in any case?

**Comment by heikki** [comment]
Not until 4.0 branch is merged.

**Comment by ibc** [comment]
Thanks for clarifying it.

**Comment by apexskier** [comment]
If anyone's testing gulp 4 in a project and doesn't want to install gulp globally, you can reference the local gulp 4.0 with `$(npm bin)/gulp`.

**Comment by phated** [comment]
Yes, we are still shipping the CLI with the main gulp package so using gulp with npm scripts is easy and doesn't require another dependency; However, if you use gulp from global at all, then installing the CLI globally avoids having to install gulp globally.

**Comment by rajathms** [comment]
I'm new to gulp.
 
I'm getting the similar error  when i run gulp command

>  package.json

`json
"dependencies": {
     "gulp": "gulpjs/gulp#4ed9a4a3275559c73a396eff7e1fde3824951ebb",
}`

```
bash
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

```

Even I tried running npm install -g "gulpjs/gulp-cli#4.0" as @heikki said

My present version is
CLI version 3.9.1
Local version 4.0.0-alpha.2

**Comment by xzegga** [comment]
@rajathms did you resolve your problem, I have the similar problem when I run gulp command. same versin for global and local gulp.

**Comment by rajathms** [comment]
@xzegga yep I resolved it , it's working.

Bring back your **CLI version to 1.2.2**  it will support gulp 4 .

when run `gulp -v`

you should get 
**[11:38:36] CLI version 1.2.2
[11:38:36] Local version 4.0.0-alpha.2**

**Comment by Niceplace** [comment]
I confirm that the solution proposed by @rajathms works !

I did : `sudo npm install gulp-cli@1.2.2 -g`

**Comment by mattjared** [comment]
Random for anyone else using @rajathms solution and still getting the wrong version output on `gulp -v`. I messed around w/ my nvm versions as well and took me forever to figure it out but close and reopen your terminal window and check the versions again. It might be cached for whatever reason in your terminal window. 🍺

**Comment by Braudin** [comment]
La solución de @rajathms funciono para mi Luego de eso tuve un error de incompatibilidad de sass para w10 x64 el cual solucione con este articulo [https://qiita.com/n0bisuke/items/7c683fd70e398ad678b9](url)
