### ISSUE TITLE
local gulp as transitive dependency not found when in a shrinkwrapped direct dependency

### ISSUE THREAD

**Issue by JustinTullgren** [gulpjs/gulp-cli#95]
Hi,

We have a 'build' npm package that wraps gulp.  This package has two business goals: to control the versions of build dependencies (like gulp, gulp help, gulp debug, less, eslint, webpack, etc) and to provide a common set of tasks to a dependent package.  The tasks are built using convention over configuration but we do allow for extension by exposing the gulp instance and the configuration object we use in the common tasks both as an export and in the return object we send back to callers in the default export.

We have multiple apps that depend on this 'build' package as their sole dependency allowing us to not have to manage multiple packages build dependencies and to allow devs to switch between projects and have a common set of tasks.  

Gulp-cli was able to access the local gulp instance because npm flattens dependencies (including transitive) and gulp was brought in through our 'build' package.  This allowed gulp-cli via Liftoff to find the local gulp directly in node_modules.

However, a few weeks ago a bug was introduced in a patch version of a transitive dependency for webpack (one of our build dependencies) breaking all of our CI and deployment builds as we always do a fresh npm install or npm update.

We decided to finally shrinkwrap our 'build' package before we publish.  However by doing this npm handles the installation of packages differently.  Npm now installs the transitive dependencies in the direct 'build' dependency's node_modules and does not flatten them which means gulp-cli can't find the local gulp.

eg

- node_modules
  - build-package
  - gulp

became

- node_modules
  - build-package
    - node_modules
      - gulp

I understand why this is the desired behavior of npm and that our situation may be atypical and that we may be abusing the use of transitive dependencies vs declaring them as explicit dependencies.

I also understand we could use node directly (`node gulpfile.js`) but then we lose the goodness of what gulp cli give us.

Is there a way for us to provide gulp-cli our local gulp instance inside our gulp file? Exporting it as a const in the gulp file does not work and we don't want to directly have to depend on gulp in each app as we then have to manage our version of gulp in many places and I think we wouldn't be sharing the same instance.

Many thanks!

info:
node 5.8
npm 3.8.2
gulp 3.9.1

**Comment by phated** [comment]
Like you said, this is an npm behavior and we can't really work around it.  You might be able to do some hacky things with the `--cwd` CLI flag but I'm not sure what that would look like.

We are attempting to solve the shared build logic with Custom Registries in gulp 4 (not yet released), but it seems like you are still using 3.9.1 so that doesn't really help the current situation either.
