### ISSUE TITLE
Installed Gulp CLI but it won't run gulp

### ISSUE THREAD

**Issue by no1melman** [gulpjs/gulp-cli#96]
So I did completely fresh install

> npm install gulp-cli

Then created simple `gulpfile.js`

```
let gulp = require('gulp');

gulp.task('build', cb => {
    console.log('Building');
    cb();
});

gulp.task('watch', gulp.series('build', cb => {
    console.log('Watching');
    cb();
}));
```

Then executed

> C:\Users\____\Documents\Git\trash
> λ gulp -v
> [23:23:44] CLI version 1.2.2

> C:\Users\____\Documents\Git\trash
> λ gulp watch
> [23:23:49] Local gulp not found in ~\Documents\Git\trash
> [23:23:49] Try running: npm install gulp

But obviously if I install `gulp` then it's not going to work because only `gulp-cli` has `series` and `parallel` functions

What is the issue here?

---

Does it require me to pull down 4.0 branch from gulp???

---

So I cloned `git clone https://github.com/gulpjs/gulp.git --branch 4.0 --single-branch` and ran `npm install` in that gulp directory, then when I did `gulp build` it worked.

I don't remember having to do this the last time I installed the `gulp-cli`

**Comment by heikki** [comment]
https://github.com/gulpjs/gulp/blob/4.0/docs/getting-started.md

**Comment by heikki** [comment]
Fairly recent instructions here: https://www.liquidlight.co.uk/blog/article/how-do-i-update-to-gulp-4/

**Comment by no1melman** [comment]
Yeah that's where I got the idea for cloning from, mainly because 

> npm install 'gulpjs/gulp.git#4.0' --save-dev

Failed for me with some horrible errors about authentication etc..

**Comment by phated** [comment]
not sure why you have that in single-quotes.  gulp has __always__ required a local version, and gulp-cli is no exception.  It's just how node works.

**Comment by no1melman** [comment]
That may be so, but when I first installed gulp-cli I removed all gulp packages first. So it must have added them itself, now it just isn't doing that hence the question.

I copied that from the blog post, is not supposed to have single quotes then?
